version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always # mindig futnia kell
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80' #localhoston 3050 portot kell nézni
  api:
    build:
      dockerfile: Dockerfile.dev #nincs mappa csak filenév
      context: ./server # itt adjuk meg neki hol dolgozzon
    volumes:
      - /app/node_modules # ne próbáld újraírni
      - ./server:/app #tükrözve lesz később nem kell újraépíteni ha változtatunk
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  #default valuek doccker hubon kiderül
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules # nem kerül felülírásra konténeren belül
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379